-- Attendance Management System schema and update SQL
-- Target API project: F:\All_Database\www\cashbook_api
-- Existing references:
--   com_companies.id
--   com_branches.id
--   hrm_employees.id
--   users.id
--   hrm_salary_payments.id

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `hrm_attendance_shifts` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `company_id` INT UNSIGNED NOT NULL,
    `branch_id` INT UNSIGNED NULL DEFAULT NULL,
    `name` VARCHAR(120) NOT NULL,
    `code` VARCHAR(40) NULL DEFAULT NULL,
    `start_time` TIME NOT NULL,
    `end_time` TIME NOT NULL,
    `grace_minutes` SMALLINT UNSIGNED NOT NULL DEFAULT 15,
    `half_day_minutes` SMALLINT UNSIGNED NOT NULL DEFAULT 240,
    `minimum_work_minutes` SMALLINT UNSIGNED NOT NULL DEFAULT 240,
    `early_out_minutes` SMALLINT UNSIGNED NOT NULL DEFAULT 60,
    `late_deduction_after_count` SMALLINT UNSIGNED NOT NULL DEFAULT 3,
    `early_out_deduction_after_count` SMALLINT UNSIGNED NOT NULL DEFAULT 3,
    `is_night_shift` TINYINT(1) NOT NULL DEFAULT 0,
    `status` TINYINT(1) NOT NULL DEFAULT 1,
    `created_by` INT UNSIGNED NULL DEFAULT NULL,
    `updated_by` INT UNSIGNED NULL DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_hrm_attendance_shifts_company` (`company_id`),
    KEY `idx_hrm_attendance_shifts_branch` (`branch_id`),
    KEY `idx_hrm_attendance_shifts_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_attendance_policies` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `company_id` INT UNSIGNED NOT NULL,
    `branch_id` INT UNSIGNED NULL DEFAULT NULL,
    `branch_type_id` INT UNSIGNED NULL DEFAULT NULL,
    `name` VARCHAR(150) NOT NULL,
    `employment_type` ENUM('monthly','daily','shifting') NOT NULL DEFAULT 'monthly',
    `shift_id` INT UNSIGNED NULL DEFAULT NULL,
    `default_shift_id` INT UNSIGNED NULL DEFAULT NULL,
    `standard_work_minutes` SMALLINT UNSIGNED NOT NULL DEFAULT 480,
    `minimum_work_minutes` SMALLINT UNSIGNED NOT NULL DEFAULT 240,
    `grace_minutes` SMALLINT UNSIGNED NOT NULL DEFAULT 15,
    `late_deduction_after_count` SMALLINT UNSIGNED NOT NULL DEFAULT 3,
    `early_out_minutes` SMALLINT UNSIGNED NOT NULL DEFAULT 60,
    `early_out_deduction_after_count` SMALLINT UNSIGNED NOT NULL DEFAULT 3,
    `half_day_minutes` SMALLINT UNSIGNED NOT NULL DEFAULT 240,
    `overtime_after_minutes` SMALLINT UNSIGNED NOT NULL DEFAULT 480,
    `absent_deduction_basis` ENUM('gross_salary_30','basic_salary_30','working_days') NOT NULL DEFAULT 'gross_salary_30',
    `sandwich_leave_enabled` TINYINT(1) NOT NULL DEFAULT 1,
    `overtime_enabled` TINYINT(1) NOT NULL DEFAULT 0,
    `monthly_salary_overtime_enabled` TINYINT(1) NOT NULL DEFAULT 0,
    `missing_out_requires_approval` TINYINT(1) NOT NULL DEFAULT 1,
    `manual_attendance_requires_approval` TINYINT(1) NOT NULL DEFAULT 1,
    `is_default` TINYINT(1) NOT NULL DEFAULT 0,
    `status` TINYINT(1) NOT NULL DEFAULT 1,
    `created_by` INT UNSIGNED NULL DEFAULT NULL,
    `updated_by` INT UNSIGNED NULL DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_hrm_attendance_policies_company` (`company_id`),
    KEY `idx_hrm_attendance_policies_branch` (`branch_id`),
    KEY `idx_hrm_attendance_policies_branch_type` (`branch_type_id`),
    KEY `idx_hrm_attendance_policies_shift` (`shift_id`),
    KEY `idx_hrm_attendance_policies_default_shift` (`default_shift_id`),
    KEY `idx_hrm_attendance_policies_type` (`employment_type`),
    KEY `idx_hrm_attendance_policies_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_employee_shift_rosters` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `company_id` INT UNSIGNED NOT NULL,
    `employee_id` INT UNSIGNED NOT NULL,
    `branch_id` INT UNSIGNED NULL DEFAULT NULL,
    `shift_id` INT UNSIGNED NOT NULL,
    `duty_date` DATE NOT NULL,
    `status` ENUM('scheduled','completed','cancelled') NOT NULL DEFAULT 'scheduled',
    `remarks` VARCHAR(255) NULL DEFAULT NULL,
    `created_by` INT UNSIGNED NULL DEFAULT NULL,
    `updated_by` INT UNSIGNED NULL DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_hrm_shift_roster_employee_date` (`employee_id`, `duty_date`),
    KEY `idx_hrm_shift_rosters_company_date` (`company_id`, `duty_date`),
    KEY `idx_hrm_shift_rosters_branch_date` (`branch_id`, `duty_date`),
    KEY `idx_hrm_shift_rosters_shift` (`shift_id`),
    KEY `idx_hrm_shift_rosters_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_weekly_holiday_policies` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `company_id` INT UNSIGNED NOT NULL,
    `branch_id` INT UNSIGNED NULL DEFAULT NULL,
    `branch_type_id` INT UNSIGNED NULL DEFAULT NULL,
    `department_id` INT UNSIGNED NULL DEFAULT NULL,
    `day_of_week` TINYINT UNSIGNED NOT NULL COMMENT '0=Sunday, 1=Monday, ..., 6=Saturday',
    `is_enabled` TINYINT(1) NOT NULL DEFAULT 1,
    `effective_from` DATE NULL DEFAULT NULL,
    `effective_to` DATE NULL DEFAULT NULL,
    `remarks` VARCHAR(255) NULL DEFAULT NULL,
    `created_by` INT UNSIGNED NULL DEFAULT NULL,
    `updated_by` INT UNSIGNED NULL DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_hrm_weekly_holidays_company` (`company_id`),
    KEY `idx_hrm_weekly_holidays_branch` (`branch_id`),
    KEY `idx_hrm_weekly_holidays_branch_type` (`branch_type_id`),
    KEY `idx_hrm_weekly_holidays_day` (`day_of_week`),
    KEY `idx_hrm_weekly_holidays_enabled` (`is_enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_holiday_calendars` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `company_id` INT UNSIGNED NOT NULL,
    `branch_id` INT UNSIGNED NULL DEFAULT NULL,
    `branch_type_id` INT UNSIGNED NULL DEFAULT NULL,
    `department_id` INT UNSIGNED NULL DEFAULT NULL,
    `holiday_date` DATE NOT NULL,
    `holiday_name` VARCHAR(180) NOT NULL,
    `holiday_type` ENUM('government','festival','company','optional','project','weekly','other') NOT NULL DEFAULT 'company',
    `is_paid` TINYINT(1) NOT NULL DEFAULT 1,
    `is_optional` TINYINT(1) NOT NULL DEFAULT 0,
    `remarks` VARCHAR(255) NULL DEFAULT NULL,
    `status` TINYINT(1) NOT NULL DEFAULT 1,
    `created_by` INT UNSIGNED NULL DEFAULT NULL,
    `updated_by` INT UNSIGNED NULL DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_hrm_holiday_scope_date_name` (`company_id`, `branch_id`, `branch_type_id`, `department_id`, `holiday_date`, `holiday_name`),
    KEY `idx_hrm_holidays_company_date` (`company_id`, `holiday_date`),
    KEY `idx_hrm_holidays_branch_date` (`branch_id`, `holiday_date`),
    KEY `idx_hrm_holidays_type` (`holiday_type`),
    KEY `idx_hrm_holidays_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_leave_types` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `company_id` INT UNSIGNED NOT NULL,
    `name` VARCHAR(120) NOT NULL,
    `code` VARCHAR(40) NOT NULL,
    `yearly_quota` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `is_paid` TINYINT(1) NOT NULL DEFAULT 1,
    `allow_half_day` TINYINT(1) NOT NULL DEFAULT 1,
    `allow_backdated` TINYINT(1) NOT NULL DEFAULT 1,
    `requires_attachment` TINYINT(1) NOT NULL DEFAULT 0,
    `sort_order` INT UNSIGNED NOT NULL DEFAULT 0,
    `status` TINYINT(1) NOT NULL DEFAULT 1,
    `created_by` INT UNSIGNED NULL DEFAULT NULL,
    `updated_by` INT UNSIGNED NULL DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_hrm_leave_types_company_code` (`company_id`, `code`),
    KEY `idx_hrm_leave_types_company` (`company_id`),
    KEY `idx_hrm_leave_types_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_leave_balances` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `company_id` INT UNSIGNED NOT NULL,
    `employee_id` INT UNSIGNED NOT NULL,
    `leave_type_id` INT UNSIGNED NOT NULL,
    `leave_year` SMALLINT UNSIGNED NOT NULL,
    `opening_balance` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `yearly_quota` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `used_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `pending_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `adjusted_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `expired_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `remaining_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `created_by` INT UNSIGNED NULL DEFAULT NULL,
    `updated_by` INT UNSIGNED NULL DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_hrm_leave_balance_employee_type_year` (`employee_id`, `leave_type_id`, `leave_year`),
    KEY `idx_hrm_leave_balances_company_year` (`company_id`, `leave_year`),
    KEY `idx_hrm_leave_balances_leave_type` (`leave_type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_leave_applications` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `company_id` INT UNSIGNED NOT NULL,
    `branch_id` INT UNSIGNED NULL DEFAULT NULL,
    `employee_id` INT UNSIGNED NOT NULL,
    `leave_type_id` INT UNSIGNED NOT NULL,
    `from_date` DATE NOT NULL,
    `to_date` DATE NOT NULL,
    `requested_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `approved_paid_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `approved_unpaid_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `sandwich_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `reason` TEXT NULL,
    `attachment_path` VARCHAR(255) NULL DEFAULT NULL,
    `application_date` DATE NOT NULL,
    `approval_status` ENUM('pending','approved','rejected','cancelled') NOT NULL DEFAULT 'pending',
    `approved_by` INT UNSIGNED NULL DEFAULT NULL,
    `approved_at` DATETIME NULL DEFAULT NULL,
    `approval_remarks` TEXT NULL,
    `rejected_by` INT UNSIGNED NULL DEFAULT NULL,
    `rejected_at` DATETIME NULL DEFAULT NULL,
    `rejection_reason` TEXT NULL,
    `created_by` INT UNSIGNED NULL DEFAULT NULL,
    `updated_by` INT UNSIGNED NULL DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_hrm_leave_applications_company` (`company_id`),
    KEY `idx_hrm_leave_applications_branch` (`branch_id`),
    KEY `idx_hrm_leave_applications_employee` (`employee_id`),
    KEY `idx_hrm_leave_applications_leave_type` (`leave_type_id`),
    KEY `idx_hrm_leave_applications_dates` (`from_date`, `to_date`),
    KEY `idx_hrm_leave_applications_status` (`approval_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_leave_application_dates` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `leave_application_id` INT UNSIGNED NOT NULL,
    `company_id` INT UNSIGNED NOT NULL,
    `employee_id` INT UNSIGNED NOT NULL,
    `leave_date` DATE NOT NULL,
    `day_value` DECIMAL(3,2) NOT NULL DEFAULT 1.00,
    `day_source` ENUM('requested','sandwich_holiday','sandwich_weekly_holiday') NOT NULL DEFAULT 'requested',
    `pay_status` ENUM('paid','unpaid','absent') NOT NULL DEFAULT 'paid',
    `approval_status` ENUM('pending','approved','rejected','cancelled') NOT NULL DEFAULT 'pending',
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_hrm_leave_application_date` (`leave_application_id`, `leave_date`),
    KEY `idx_hrm_leave_dates_employee_date` (`employee_id`, `leave_date`),
    KEY `idx_hrm_leave_dates_company_date` (`company_id`, `leave_date`),
    KEY `idx_hrm_leave_dates_status` (`approval_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_attendance_entries` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `company_id` INT UNSIGNED NOT NULL,
    `branch_id` INT UNSIGNED NULL DEFAULT NULL,
    `employee_id` INT UNSIGNED NOT NULL,
    `shift_id` INT UNSIGNED NULL DEFAULT NULL,
    `attendance_date` DATE NOT NULL,
    `shift_start_at` DATETIME NULL DEFAULT NULL,
    `shift_end_at` DATETIME NULL DEFAULT NULL,
    `in_time` DATETIME NULL DEFAULT NULL,
    `out_time` DATETIME NULL DEFAULT NULL,
    `work_minutes` INT UNSIGNED NOT NULL DEFAULT 0,
    `overtime_minutes` INT UNSIGNED NOT NULL DEFAULT 0,
    `overtime_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    `attendance_source` ENUM('manual','biometric','mobile','web','gps') NOT NULL DEFAULT 'manual',
    `device_id` INT UNSIGNED NULL DEFAULT NULL,
    `device_employee_code` VARCHAR(80) NULL DEFAULT NULL,
    `gps_latitude` DECIMAL(10,7) NULL DEFAULT NULL,
    `gps_longitude` DECIMAL(10,7) NULL DEFAULT NULL,
    `status` ENUM('present','absent','half_day','leave','holiday','weekly_holiday','late','early_out','pending','rejected') NOT NULL DEFAULT 'pending',
    `is_late` TINYINT(1) NOT NULL DEFAULT 0,
    `late_minutes` INT UNSIGNED NOT NULL DEFAULT 0,
    `is_early_out` TINYINT(1) NOT NULL DEFAULT 0,
    `early_out_minutes` INT UNSIGNED NOT NULL DEFAULT 0,
    `is_half_day` TINYINT(1) NOT NULL DEFAULT 0,
    `is_manual` TINYINT(1) NOT NULL DEFAULT 1,
    `requires_approval` TINYINT(1) NOT NULL DEFAULT 1,
    `approval_status` ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
    `approved_by` INT UNSIGNED NULL DEFAULT NULL,
    `approved_at` DATETIME NULL DEFAULT NULL,
    `approval_remarks` TEXT NULL,
    `rejected_by` INT UNSIGNED NULL DEFAULT NULL,
    `rejected_at` DATETIME NULL DEFAULT NULL,
    `rejection_reason` TEXT NULL,
    `remarks` TEXT NULL,
    `created_by` INT UNSIGNED NULL DEFAULT NULL,
    `updated_by` INT UNSIGNED NULL DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_hrm_attendance_employee_date` (`employee_id`, `attendance_date`),
    KEY `idx_hrm_attendance_entries_company_date` (`company_id`, `attendance_date`),
    KEY `idx_hrm_attendance_entries_branch_date` (`branch_id`, `attendance_date`),
    KEY `idx_hrm_attendance_entries_employee_date` (`employee_id`, `attendance_date`),
    KEY `idx_hrm_attendance_entries_shift` (`shift_id`),
    KEY `idx_hrm_attendance_entries_status` (`status`),
    KEY `idx_hrm_attendance_entries_approval` (`approval_status`),
    KEY `idx_hrm_attendance_entries_source` (`attendance_source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_attendance_approvals` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `attendance_entry_id` INT UNSIGNED NOT NULL,
    `company_id` INT UNSIGNED NOT NULL,
    `employee_id` INT UNSIGNED NOT NULL,
    `action` ENUM('submitted','approved','rejected','corrected','cancelled') NOT NULL,
    `action_by` INT UNSIGNED NULL DEFAULT NULL,
    `action_at` DATETIME NOT NULL,
    `remarks` TEXT NULL,
    `previous_data` LONGTEXT NULL,
    `new_data` LONGTEXT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_hrm_attendance_approvals_entry` (`attendance_entry_id`),
    KEY `idx_hrm_attendance_approvals_company` (`company_id`),
    KEY `idx_hrm_attendance_approvals_employee` (`employee_id`),
    KEY `idx_hrm_attendance_approvals_action` (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_attendance_monthly_summaries` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `company_id` INT UNSIGNED NOT NULL,
    `branch_id` INT UNSIGNED NULL DEFAULT NULL,
    `employee_id` INT UNSIGNED NOT NULL,
    `salary_payment_id` INT UNSIGNED NULL DEFAULT NULL,
    `summary_month` CHAR(7) NOT NULL COMMENT 'YYYY-MM',
    `month_days` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `present_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `leave_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `paid_leave_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `unpaid_leave_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `holiday_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `weekly_holiday_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `absent_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `half_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `late_count` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    `late_deduction_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `early_out_count` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    `early_out_deduction_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `overtime_minutes` INT UNSIGNED NOT NULL DEFAULT 0,
    `overtime_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    `payable_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `deduction_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    `gross_salary` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    `per_day_salary` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    `attendance_deduction_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    `calculation_snapshot` LONGTEXT NULL,
    `generated_by` INT UNSIGNED NULL DEFAULT NULL,
    `generated_at` DATETIME NULL DEFAULT NULL,
    `locked_at` DATETIME NULL DEFAULT NULL,
    `locked_by` INT UNSIGNED NULL DEFAULT NULL,
    `status` ENUM('draft','generated','locked','cancelled') NOT NULL DEFAULT 'draft',
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_hrm_attendance_summary_employee_month` (`employee_id`, `summary_month`),
    KEY `idx_hrm_attendance_summaries_company_month` (`company_id`, `summary_month`),
    KEY `idx_hrm_attendance_summaries_branch_month` (`branch_id`, `summary_month`),
    KEY `idx_hrm_attendance_summaries_salary_payment` (`salary_payment_id`),
    KEY `idx_hrm_attendance_summaries_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_attendance_summary_details` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `summary_id` INT UNSIGNED NOT NULL,
    `company_id` INT UNSIGNED NOT NULL,
    `branch_id` INT UNSIGNED NULL DEFAULT NULL,
    `employee_id` INT UNSIGNED NOT NULL,
    `attendance_date` DATE NOT NULL,
    `attendance_entry_id` INT UNSIGNED NULL DEFAULT NULL,
    `leave_application_id` INT UNSIGNED NULL DEFAULT NULL,
    `day_status` ENUM('present','absent','half_day','paid_leave','unpaid_leave','holiday','weekly_holiday','late','early_out') NOT NULL,
    `day_value` DECIMAL(3,2) NOT NULL DEFAULT 1.00,
    `payable_value` DECIMAL(3,2) NOT NULL DEFAULT 1.00,
    `deduction_value` DECIMAL(3,2) NOT NULL DEFAULT 0.00,
    `remarks` VARCHAR(255) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_hrm_attendance_summary_detail_date` (`summary_id`, `attendance_date`),
    KEY `idx_hrm_attendance_summary_details_employee_date` (`employee_id`, `attendance_date`),
    KEY `idx_hrm_attendance_summary_details_status` (`day_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_attendance_devices` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `company_id` INT UNSIGNED NOT NULL,
    `branch_id` INT UNSIGNED NULL DEFAULT NULL,
    `device_name` VARCHAR(150) NOT NULL,
    `device_code` VARCHAR(100) NULL DEFAULT NULL,
    `device_type` ENUM('biometric','mobile','web','gps','other') NOT NULL DEFAULT 'biometric',
    `ip_address` VARCHAR(80) NULL DEFAULT NULL,
    `serial_no` VARCHAR(120) NULL DEFAULT NULL,
    `status` TINYINT(1) NOT NULL DEFAULT 1,
    `last_sync_at` DATETIME NULL DEFAULT NULL,
    `created_by` INT UNSIGNED NULL DEFAULT NULL,
    `updated_by` INT UNSIGNED NULL DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_hrm_attendance_devices_company` (`company_id`),
    KEY `idx_hrm_attendance_devices_branch` (`branch_id`),
    KEY `idx_hrm_attendance_devices_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_attendance_device_employees` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `company_id` INT UNSIGNED NOT NULL,
    `device_id` INT UNSIGNED NOT NULL,
    `employee_id` INT UNSIGNED NOT NULL,
    `device_employee_code` VARCHAR(80) NOT NULL,
    `status` TINYINT(1) NOT NULL DEFAULT 1,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_hrm_device_employee_code` (`device_id`, `device_employee_code`),
    UNIQUE KEY `uq_hrm_device_employee` (`device_id`, `employee_id`),
    KEY `idx_hrm_device_employees_company` (`company_id`),
    KEY `idx_hrm_device_employees_employee` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hrm_attendance_audit_logs` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `company_id` INT UNSIGNED NULL DEFAULT NULL,
    `branch_id` INT UNSIGNED NULL DEFAULT NULL,
    `employee_id` INT UNSIGNED NULL DEFAULT NULL,
    `auditable_type` VARCHAR(120) NOT NULL,
    `auditable_id` INT UNSIGNED NULL DEFAULT NULL,
    `action` VARCHAR(60) NOT NULL,
    `old_values` LONGTEXT NULL,
    `new_values` LONGTEXT NULL,
    `reason` TEXT NULL,
    `created_by` INT UNSIGNED NULL DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_hrm_attendance_audit_company` (`company_id`),
    KEY `idx_hrm_attendance_audit_branch` (`branch_id`),
    KEY `idx_hrm_attendance_audit_employee` (`employee_id`),
    KEY `idx_hrm_attendance_audit_auditable` (`auditable_type`, `auditable_id`),
    KEY `idx_hrm_attendance_audit_action` (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Existing table updates
-- Run this update section once. If any column/index already exists, skip that specific ALTER statement.

ALTER TABLE `hrm_employees`
    ADD COLUMN `employment_type` ENUM('monthly','daily','shifting') NOT NULL DEFAULT 'monthly',
    ADD COLUMN `attendance_shift_id` INT UNSIGNED NULL DEFAULT NULL,
    ADD COLUMN `default_shift_id` INT UNSIGNED NULL DEFAULT NULL,
    ADD COLUMN `device_employee_code` VARCHAR(80) NULL DEFAULT NULL,
    ADD COLUMN `attendance_policy_id` INT UNSIGNED NULL DEFAULT NULL,
    ADD COLUMN `overtime_eligible` TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN `daily_wage` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN `ot_rate` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN `standard_work_minutes` SMALLINT UNSIGNED NULL DEFAULT NULL,
    ADD INDEX `idx_hrm_employees_employment_type` (`employment_type`),
    ADD INDEX `idx_hrm_employees_attendance_shift_id` (`attendance_shift_id`),
    ADD INDEX `idx_hrm_employees_default_shift_id` (`default_shift_id`),
    ADD INDEX `idx_hrm_employees_attendance_policy_id` (`attendance_policy_id`),
    ADD INDEX `idx_hrm_employees_device_employee_code` (`device_employee_code`);

ALTER TABLE `hrm_salary_payments`
    ADD COLUMN `attendance_summary_id` INT UNSIGNED NULL DEFAULT NULL,
    ADD COLUMN `attendance_working_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN `attendance_absent_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN `attendance_unpaid_leave_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN `attendance_half_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN `attendance_late_count` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN `attendance_late_deduction_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN `attendance_early_out_count` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN `attendance_early_out_deduction_days` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN `attendance_deduction_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN `attendance_snapshot` LONGTEXT NULL,
    ADD INDEX `idx_hrm_salary_payments_attendance_summary_id` (`attendance_summary_id`);

-- Upgrade legacy attendance table.
ALTER TABLE `hrm_attendances`
    ADD COLUMN `company_id` INT UNSIGNED NULL DEFAULT NULL,
    ADD COLUMN `branch_id` INT UNSIGNED NULL DEFAULT NULL,
    ADD COLUMN `shift_id` INT UNSIGNED NULL DEFAULT NULL,
    ADD COLUMN `work_minutes` INT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN `attendance_source` VARCHAR(30) NOT NULL DEFAULT 'manual',
    ADD COLUMN `attendance_status` VARCHAR(30) NOT NULL DEFAULT 'present',
    ADD COLUMN `approval_status` VARCHAR(30) NOT NULL DEFAULT 'pending',
    ADD COLUMN `approved_by` INT UNSIGNED NULL DEFAULT NULL,
    ADD COLUMN `approved_at` DATETIME NULL DEFAULT NULL,
    ADD COLUMN `remarks` TEXT NULL,
    ADD INDEX `idx_hrm_attendances_employee_date` (`employee_id`, `attendance_date`),
    ADD INDEX `idx_hrm_attendances_branch_date` (`branch_id`, `attendance_date`),
    ADD INDEX `idx_hrm_attendances_approval_status` (`approval_status`);

-- Upgrade legacy holiday/working-day tables.
ALTER TABLE `hrm_holydays`
    ADD COLUMN `branch_type_id` INT UNSIGNED NULL DEFAULT NULL,
    ADD COLUMN `holiday_type` VARCHAR(40) NOT NULL DEFAULT 'company',
    ADD COLUMN `is_paid` TINYINT(1) NOT NULL DEFAULT 1,
    ADD INDEX `idx_hrm_holydays_company_holiday` (`company_id`, `holiday`);

ALTER TABLE `hrm_working_days`
    ADD COLUMN `company_id` INT UNSIGNED NULL DEFAULT NULL,
    ADD COLUMN `branch_id` INT UNSIGNED NULL DEFAULT NULL,
    ADD COLUMN `branch_type_id` INT UNSIGNED NULL DEFAULT NULL,
    ADD COLUMN `is_weekly_holiday` TINYINT(1) NOT NULL DEFAULT 0,
    ADD INDEX `idx_hrm_working_days_company_branch` (`company_id`, `branch_id`);
