export const MENU_PERMISSIONS = {
  transaction: [
    'cash.received.create',
    'cash.payment.create',
    'bank.received.create',
    'bank.payment.create',
    'hrm.loan.create',
    'journal.create',
    'branch.transfer.create',
    'branch.received.create',
    'inventory.transfer.create',
    'inventory.received.create',
    'product.transfer.create',
    'product.received.create',
  ],
  invoice: ['purchase.create', 'sales.create', 'labour.invoice.create'],
  reports: [
    'cashbook.view',
    'installment.create',
    'ledger.view',
    'ledger.labour',
    'ledger.due.view',
    // Ledger Details (Customer Supplier Statement) hangs off this menu on
    // either of these, so both have to open the parent -- otherwise the only
    // permission a user holds gates a screen they can never reach the menu for.
    'ledger.customer',
    'ledger.details',
    'date.wise.total',
    // The Expense Report is only ever reached through this menu, so the
    // permission that shows the entry has to open the parent group too --
    // otherwise a user holding just this one never sees Reports at all.
    'expense.report',
    'product.stock.view',
    'product.in.out',
    'purchase.ledger',
    'sales.ledger',
    'group.report',
    'mitch.match',
    'productwise.profit',
  ],
  requisition: ['requisition.view', 'requisition.create', 'requisition.comparison'],
  products: ['products.view'],
  admin: [
    'check.register.view',
    'branch.view',
    'all.user.view',
    'dayclose.create',
    'order.view',
    'order.avg.price',
    'voucher.approval',
    'remove.approval',
    'change.vourcher.type',
    'voucher.photo.upload',
    'voucher.photo.delete',
    'bulk.photo.upload',
    'roles.view',
    'roles.create',
    'roles.edit',
    'roles.delete',
    'reseller.view',
  ],
  voucher_settings: [
    'voucher.delete',
    'installment.delete',
    'voucher.date.change',
    'voucher.recycle',
    'voucher.history',
    // The Log Changes screen. The permission the backend actually creates is
    // 'log.changes' (Voucher Modification group); 'voucher.changes' was never
    // one, so a user holding only this was kept out of the parent menu here
    // and bounced to /no-access by the route guard.
    'log.changes',
  ],
  hrm: [
    'employee.view',
    'attendance.view',
    'attendance.create',
    'attendance.approve',
    'leave.view',
    'leave.approve',
    'holiday.view',
    'shift.view',
    'salary.generate',
    'salary.sheet.view',
    'employee.loan.ledger.view',
  ],
  roles: ['roles.view', 'roles.create', 'roles.edit', 'roles.delete'],
  customer: [
    'cs.delete',
    'cs.edit',
    'cs.information',
    'cs.ledger',
    'cs.photo.delete',
    'cs.photo.edit',
    'cs.photo.update',
    'cs.photo.view',
    'cs.update',
    'cs.view',
    'coa.l1.view',
    'coa.l2.view',
    'coa.l3.view',
    'coa.l4.view',
  ],
  chart_of_accounts: [
    'coa.l1.view',
    'coa.l2.view',
    'coa.l3.view',
    'coa.l4.view',
  ],
  analytics: ['analytics.comparison'],
  real_estate: ['real.estate.view'],
  reseller: ['reseller.dashboard.view'],
  subscription_history: ['subscription.view', 'subscription.history'],
  customer_dashboard: ['customer.dashboard'],
};
