export const MENU_PERMISSIONS = {
  transaction: [
    'cash.received.create',
    'cash.payment.create',
    'bank.received.create',
    'bank.payment.create',
    'hrm.loan.create',
    'journal.create',
  ],
  invoice: ['purchase.create', 'sales.create', 'labour.invoice.create'],
  reports: [
    'cashbook.view',
    'installment.create',
    'ledger.view',
    'ledger.labour',
    'ledger.due.view',
    'date.wise.total',
    'product.stock.view',
    'product.in.out',
    'purchase.ledger',
    'sales.ledger',
    'group.report',
    'mitch.match',
  ],
  requisition: ['requisition.create', 'requisition.comparison'],
  products: ['category.view', 'products.view'],
  admin: [
    'branch.view',
    'all.user.view',
    'dayclose.create',
    'order.view',
    'order.avg.price',
    'voucher.approval',
    'remove.approval',
    'change.vourcher.type',
    'voucher.photo.upload',
    'bulk.photo.upload',
  ],
  voucher_settings: [
    'voucher.delete',
    'installment.delete',
    'voucher.delete',
    'voucher.date.change',
    'voucher.recycle',
    'voucher.history',
    'voucher.changes',
  ],
  hrm: ['employee.view', 'salary.generate', 'salary.sheet.view', 'employee.loan.ledger.view'],
  roles: ['roles.view', 'roles.create', 'roles.edit', 'roles.delete'],
  customer: [
    'cs.delete',
    'cs.edit',
    'cs.information',
    'cs.ledger',
    'cs.photo.delete',
    'cs.photo.edit',
    'cs.photo.update',
    'cs.photo.view',
    'cs.update',
    'cs.view',
  ],
};
