name: Node.js CI

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [22.x]   # চাইলে [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install
        run: npm ci

      - name: Lint (if present)
        run: |
          if npm run | grep -q "lint"; then npm run lint; else echo "No lint script — skipping"; fi

      - name: Type check (if present)
        run: |
          if npm run | grep -q "typecheck"; then npm run typecheck; else echo "No typecheck script — skipping"; fi

      - name: Build (if present)
        env:
          CI: true
        run: npm run build --if-present

      - name: Test (if present)
        env:
          CI: true
        run: |
          if npm run | grep -q "test"; then
            npm test -- --ci --coverage --watch=false
          else
            echo "No test script — skipping"
          fi

      - name: Upload build (artifact)
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: web-build
          path: |
            dist
            build
          if-no-files-found: ignore
